Fix a encoding error
When I use this build tool, it occurs this error:

	D:\3rd_projects\three.js-master\utils\build>python build.py --include common --i
	nclude extras --output ../../build/three.js
	 * Building ../../build/three.js
	Traceback (most recent call last):
	  File "build.py", line 106, in <module>
	    main()
	  File "build.py", line 65, in main
	    tmp.write(f.read())
	UnicodeDecodeError: 'gbk' codec can't decode byte 0x92 in position 5904: illegal
	 multibyte sequence

It seems that the reason lies in the default encoding of the `open` function. On my computer it's `GBK` rather than `UTF8`. So I add the `encoding` parameter to it, and then it's just all right.